import type { NextPage } from 'next'
import Head from 'next/head'
import { Timer } from '../src/components/Timer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cronômetro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.main}>
          <Timer/>
        </div>
        <div className={styles.content}>
          <h2>Cronômetro EP</h2>
          <p className={styles.paragraph}>O Cronômetro EP é um projeto que tem por objetivo ser uma ferramenta para auxiliar nas tarefas de cronometragens, na aplicação da engenharia de métodos.</p>

          <h2>Engenharia de Métodos</h2>
          <p className={styles.paragraph}>A Engenharia de Métodos é a área da engenharia responsável pela análise da carga de trabalho e implantação de métodos, com a finalidade de melhorar o rendimento do trabalho e eliminar toda operação desnecessária ou ineficiente. Portanto, estuda a concepção e a seleção da melhor organização das atividades. Avalia ainda o método mais adequado de produção, os processos, o emprego de ferramentas e equipamentos e as competências operacionais necessárias para realizar uma operação.</p>

          <h2>Estudos de tempos</h2>
          <p className={styles.paragraph}>
            Segundo Slack (2015) se não houver uma forma de quantificar o trabalho, as atividades e operações como através da estimativa de tempos não seria possível saber a melhor forma de se dividir o trabalho através de equipes ou aos funcionários, não teria como estimar o tempo necessário para o término de uma atividade, nem sequer saber se o trabalho está progredindo da forma correta, tão pouco entender os custos. Desta forma “desorientando” o gerente de produção da sua meta. A forma mais difundida e utilizada para a medição do tempo de produção ou atividade, tem sido a cronometragem. Mesmo com os grandes avanços ocorridos dentro da administração cientifica, desde os tempos de F.W. Taylor, sua metodologia sobre estudo de tempos se mantem até hoje, objetivando medir a eficiência individual (Martins & Laugenir ,2005). 
          </p>

          <p className={styles.paragraph}>
            Segundo Barnes (1977), o estudo de tempo e de movimentos é de grande utilidade para determinar o tempo padrão que é o tempo necessário para uma pessoa qualificada e devidamente treinada e com certa experiência deveria gastar para desempenhar uma determinada atividade ou operação trabalhando normalmente.
          </p>

          <p className={styles.paragraph}>
            Peinado & Graeml (2007) falam que a cronoanálise, também conhecido como estudo de tempos, é de vital importância para se determinar o tempo de operações de uma empresa, desta forma tem a capacidade de determinar a sua capacidade produtiva e concede parâmetros para a elaboração de planos estratégicos de produção. Para a determinação do tempo padrão de produção, deve-se levar em consideração a velocidade de trabalho do operador, juntamente com o fator de tolerância para atender as necessidades pessoais e para que o mesmo possa se recuperar dos efeitos da fadiga (PEINADO & GRAEML 2007).
          </p>
        </div>
      </main>
        

      <footer className={styles.footer}>
        <a
          href="https://github.com/lucassnts963"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {' '}
          <span className={styles.logo}>
            Lucas Santos
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
